//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietGioHang
    {
        public int MaCT { get; set; }
        public Nullable<int> MaGioHang { get; set; }
        public Nullable<int> MaSP { get; set; }
        public string SoLuong { get; set; }
    }
}
