//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGioHang { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string TrangThai { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    }
}
