//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int MaKM { get; set; }
        public string TenMaKM { get; set; }
        public string ThongTinKM { get; set; }
        public string GiaTienKM { get; set; }
    }
}
