//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyVeChungToi
    {
        public int MaVCT { get; set; }
        public string TenVCT { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
    }
}
