//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLyThongBao
    {
        public int MaThongBao { get; set; }
        public string TenThongBao { get; set; }
        public string NoiDung { get; set; }
    }
}
