//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyQuanAoEntities : DbContext
    {
        public QuanLyQuanAoEntities()
            : base("name=QuanLyQuanAoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KhuyenMai> KhuyenMai { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPham { get; set; }
        public virtual DbSet<ChiTietGioHang> ChiTietGioHang { get; set; }
        public virtual DbSet<FeedbackKH> FeedbackKH { get; set; }
        public virtual DbSet<QuanLySlider> QuanLySlider { get; set; }
        public virtual DbSet<QuanLyThongBao> QuanLyThongBao { get; set; }
        public virtual DbSet<QuanLyVeChungToi> QuanLyVeChungToi { get; set; }
        public virtual DbSet<SanPham> SanPham { get; set; }
        public virtual DbSet<ThongTinTaiKhoan> ThongTinTaiKhoan { get; set; }
        public virtual DbSet<ChiTietSanPham> ChiTietSanPham { get; set; }
        public virtual DbSet<GioHang> GioHang { get; set; }
    }
}
