//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyWebQuanAoMixi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string SoLuong { get; set; }
        public string ThuongHieu { get; set; }
        public string XuatXu { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public string MoTa { get; set; }
        public string GioiTinh { get; set; }
        public string GiaBan { get; set; }
        public string GhiChu { get; set; }
        public string HinhAnh { get; set; }
        public string MauSac { get; set; }
        public string KichThuoc { get; set; }
    }
}
